[tool.poetry]
name = "telethon-channel-rewrite"
version = "0.1.0"
description = ""
authors = ["mrtstg <russiankurwacsgo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
telethon = "^1.38.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
